// Code generated by mockery v1.0.0
package mocks

import funky "github.com/dispatchframework/funky/pkg/funky"
import mock "github.com/stretchr/testify/mock"

// ContextInjector is an autogenerated mock type for the ContextInjector type
type ContextInjector struct {
	mock.Mock
}

// Inject provides a mock function with given fields: req
func (_m *ContextInjector) Inject(req *funky.Request) error {
	ret := _m.Called(req)

	var r0 error
	if rf, ok := ret.Get(0).(func(*funky.Request) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
