// Code generated by mockery v1.0.0
package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// HTTPReaderWriter is an autogenerated mock type for the HTTPReaderWriter type
type HTTPReaderWriter struct {
	mock.Mock
}

// Read provides a mock function with given fields: result, req
func (_m *HTTPReaderWriter) Read(result interface{}, req *http.Request) error {
	ret := _m.Called(result, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, *http.Request) error); ok {
		r0 = rf(result, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: body, contentType, w
func (_m *HTTPReaderWriter) Write(body interface{}, contentType string, w http.ResponseWriter) error {
	ret := _m.Called(body, contentType, w)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, http.ResponseWriter) error); ok {
		r0 = rf(body, contentType, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
