// Code generated by mockery v1.0.0
package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// HTTPRequestAware is an autogenerated mock type for the HTTPRequestAware type
type HTTPRequestAware struct {
	mock.Mock
}

// SetHTTPRequest provides a mock function with given fields: req
func (_m *HTTPRequestAware) SetHTTPRequest(req *http.Request) {
	_m.Called(req)
}
