// Code generated by mockery v1.0.0
package mocks

import (
	"github.com/dispatchframework/funky/pkg/funky"
	mock "github.com/stretchr/testify/mock"
)

// ServerFactory is an autogenerated mock type for the ServerFactory type
type ServerFactory struct {
	mock.Mock
}

// CreateServer provides a mock function with given fields: port
func (_m *ServerFactory) CreateServer(port uint16) (funky.Server, error) {
	ret := _m.Called(port)

	var r0 funky.Server
	if rf, ok := ret.Get(0).(func(uint16) funky.Server); ok {
		r0 = rf(port)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(funky.Server)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint16) error); ok {
		r1 = rf(port)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
